### ISSUE TITLE
44) Bedienungs-Problem Zahleneingabe (erster Schritt)

### ISSUE THREAD

**Issue by kellerfelix** [kellerfelix/rollladenkonfigurator#1]
**Problembeschreibung:**
Wenn ich im ersten Schritt ( http://wordpress.p379232.webspaceconfig.de/vorbaurolladen-konfigurator-pvc/ ) einen Wert eintrage der kleiner ist als 50 (Minimalwert) wird es ordnungsgemäß als Fehler gewertet. 

Erhöhe ich den Wert (via hoch runter buttons) jetzt auf 50.1 oder höher wird das Feld aber immer noch als falsch ausgefüllt erkannt. Hinweis dazu: Komma-Zahl(-Darstellung) stimmt jetzt soweit, wenn ich 50,1 direkt über die Tastatur eingebe funktioniert die Überprüfung komischerweise auch. Scheint also ein Problem mit den +-Buttons zu sein. 

WICHTIG: Gilt auch für obere Grenzwerte. Bei Wert-Änderungen von 301-> 300 via Buttons wird immer noch ein Fehler angezeigt, beim Type-In klappts.

Status: Noch nicht behoben

Erster Feedback Boris: Hinweis: Die Preisberechnung scheint über die Buttons aber zu funktionieren ( es zeigen sich andere Preise wenn man die Werte über die +-Buttons verändert).

**Comment by kellerfelix** [comment]
Kurzes Update von Gespräch mit Boris:
- Möglichkeit die +- Buttons zu verbergen ist möglich. Allerdings funktioniert dann bei Felderwechsel wahrscheinlich keine Überprüfung der Werte mehr (wäre vorrübergehend zu verschmerzen). Kann man die +- Buttons ggf. sperren?
- Weitere Möglichkeit (nicht wünschenswert): Bei roten Felder/fehlenden Eingaben, alle Eingaben des aktuellen Schrittes löschen. Das wäre allerdings für den User recht nervig und fustrierend

Fazit: Alles nicht so wirklich schön, aber wir brauchen dafür dringend eine Lösung.

**Comment by betzholz** [comment]
ja hier können wir aber nicht einfach was machen, die buttos kommen nicht von uns sondern vom browser... entweder keien valdierung nach zahlen oder eben doch

**Comment by kellerfelix** [comment]
Kurzes Update von Gespräch mit Boris:
- Möglichkeit die +- Buttons zu verbergen ist möglich. Allerdings funktioniert dann bei Felderwechsel wahrscheinlich keine Überprüfung der Werte mehr (wäre vorrübergehend zu verschmerzen). Kann man die +- Buttons ggf. sperren?
- Weitere Möglichkeit (nicht wünschenswert): Bei roten Felder/fehlenden Eingaben, alle Eingaben des aktuellen Schrittes löschen. Das wäre allerdings für den User recht nervig und fustrierend

Fazit: Alles nicht so wirklich schön, aber wir brauchen dafür dringend eine Lösung.

**Comment by kellerfelix** [comment]
Status 11.06.2018: Problem noch ungelöst. Wir brauchen eine Validierung, aber keine +- Buttons. Ggf. müsste die Validierung nach jeder Eingabe im Feld ausgeführt werden (ggf. auch mit 1sek Verzögerung). Wäre das eine Möglichkeit?

**Comment by hyphone** [comment]
> ja hier können wir aber nicht einfach was machen, die buttos kommen nicht von uns sondern vom browser... entweder keien valdierung nach zahlen oder eben doch

wie wärs, wenn man auch bei onchange die Felder validieren würde :-P

@kellerfelix sollte jetzt gehen

**Comment by kellerfelix** [comment]
Hm eigentlich schon. Ich teste das nochmal auf dem Windows Rechner mit Cache leeren:

Ok gleiches Verhalten. Wenn ich von 49 auf 50 erhöhe = alles gut, keine rote Markierung. (so sollte es sein)
Wenn ich aber weiter erhöhe (per button) auf 50,1 wird das wieder als rotes Feld markiert.
Gleiches gilt für die Breite. Ändere ich den Werte per Button wieder zurück auf 50, wird die Fehlerdarstellung auch wieder entfernt. Kommt er vielleicht mit den Komma-Werten nicht klar?

Wenn ich die Werte per Tastatur eingebe werden diese zunächst als gültig angezeigt. Sobald ich aber mittels Maus ins nächste Feld klicke, wird die eigentlich gültige Eingabe (bsp höhe =51) wieder als ungültig erfasst.

Funktionieren tut es bei mir nur dann, wenn ich von hohe per TAB taste zu breite wechsele, dort etwas eingebe und dann mittels SHIFT + TAB zum letzten Feld zurückgehe. Nur dann sind beide Felder als validiert dargestellt. :(

Getestet auf Chrome/Firefox + Win10

**Comment by hyphone** [comment]
Bitte noch einmal versuchen.

**Comment by kellerfelix** [comment]
Funktioniert 1A! Gute Arbeit, vielen Dank!
