### ISSUE TITLE
P3 - Website: Ladezeiten Flatsome (später anschauen)

### ISSUE THREAD

**Issue by kellerfelix** [kellerfelix/rollladenkonfigurator#10]
Immer wieder sind die Ladezeiten ein Problem der Webseite. Beim Konfigurator gerade hat es über 32sek gedauert bis die ganze Seite geladen war. Vermutlich verantwortlich ist das Theme Flatsome:
![bildschirmfoto 2018-06-18 um 21 38 13](https://user-images.githubusercontent.com/8479367/41558176-46d4baa0-7340-11e8-9c15-52a980293cca.png)

**Comment by hyphone** [comment]
die 42KB sind ja nichts. Mittwald ist das problem, weil der Client ewig auf eine Antwort wartet.
Zieht einmal auf einen performanteren Server um (ich kann es gern auf meinen Hetzner-Account umziehen) und es sollte flutschen.

**Comment by kellerfelix** [comment]
Das macht ja sicher Sinn, das direkt beim Launch zu unternehmen. Da bei unserem derzeitigen Programmierer (Webseite) die Live-Stellung noch inklusive ist, würde ich dem das überlassen. Könntest der das auch auf deinen Hetzner Account umziehen? Danke für deinen Hinweis dazu! Ich hatte sowas auch mal vermutet, denn vorher waren wir auf einem anderen Server unterwegs und da lief es deutlich flüssiger.

**Comment by hyphone** [comment]
Sicher kann er das auch übernehmen. Die Feinheiten zum Caching bei Hetzner usw. würde ich dann anschließend, nach dem Launch, vornehmen (kein großer Aufwand). Dann wird die Seite schon flutschen.

**Comment by kellerfelix** [comment]
Der Kommentar ist etwas älter. Du müsstest den Launch wie besprochen komplett betreuen. Der gute, wenn auch etwas unfähige Mann ist leider in Urlaub ;)

**Comment by kellerfelix** [comment]
Tempo passt - closed
