### ISSUE TITLE
P1 - Konfigurator: Farbe der Endleiste als Farbwert angegeben, nicht als Farbe

### ISSUE THREAD

**Issue by kellerfelix** [kellerfelix/rollladenkonfigurator#11]
Hallo Marco,

beim Panzer-Konfigurator ( http://wordpress.p379232.webspaceconfig.de/rolladenpanzer-konfigurator-aluminium/ ) erscheint bei "Farbe der Endleiste" seit kurzem im Warenkorb nur noch der Farbwert, nicht wie gewünscht der Beschreibungstext der Elemente. Kannst du das anpassen?

Falsch:
#fffff

Korrekt:
Weiß 9016

![snipimage](https://user-images.githubusercontent.com/8479367/42043384-9a88223c-7af6-11e8-83d7-4eadd4c3224f.JPG)

**Comment by hyphone** [comment]
Hmm, dann müsste hier ein anderer Wert eingetragen werden:

![bildschirmfoto von 2018-06-30 15-40-45](https://user-images.githubusercontent.com/6410852/42125706-10da8de0-7c7c-11e8-8ad0-1b8b8d999fd2.png)

Gibt es einen Grund warum dort bspw. #ffffff oder b0b0a9 eingetragen ist?

**Comment by kellerfelix** [comment]
Ja, der Grund dafür ist dass die #Farbwerte dort als Basis für die Darstellung der Farbe im Frontend genutzt werden. Das hatte der Programmierer damals "der Einfachheit" halber so angelegt. Komisch ist, dass es immer richtig angezeigt wurde. Ggf. wurde mit einer deine Anpassungen ja eine Custom Lösung für dieses Feld überschrieben? Nicht dramatisch, aber wie lösen wir das am besten? Folgen wir der Standard-Struktur und nehmen für das Colorfeld einfach noch einen weiteren Wert im Feld dazu? Wie könnte eine Lösung dazu aussehen?

**Comment by kellerfelix** [comment]
Workaround - Bilder verwendet.
