### ISSUE TITLE
P1 - Webseite: Weiter-Einkaufen Button führt aufs falsche Ziel

### ISSUE THREAD

**Issue by kellerfelix** [kellerfelix/rollladenkonfigurator#13]
Hallo Marco,

wenn ich derzeit etwas in den Warenkorb lege, habe ich die Möglichkeit dann auf einen Button "weiter einkaufen" zu klicken. Dieser führt mich allerdings auf eine ganz merkwürdige uralte Seite: 

http://wordpress.p379232.webspaceconfig.de/shop-2018

Da ich die Seite nicht groß bearbeiten kann, habe ich vermutet, dass es sich hier um die Standard-Woocommerce-Shop Seite (Produktübersicht mit Kategorien) handelt. Diese haben wir allerdings durch den Programmierer ersetzen lassen und derzeit führt zumindest der Link SHOP auf http://wordpress.p379232.webspaceconfig.de/shop/

So soll das auch bleiben. Können wir die 2018-URL entfernen oder einfach den Link im Theme ändern?

**Comment by hyphone** [comment]
Es gab 2 Shop-Seiten, einmal "Shop" und "Shop 2018", die in WC als Shop-Seite definiert war und daher herangezogen wurde. Habe Shop 2018 in den Papierkorb gelegt und "Shop" als "Shop-Seite" in WC definiert.

**Comment by kellerfelix** [comment]
Kommentar aus der Mail von vorhin:
Das Löschen der shop-2018 Seite war leider keine gute Idee. Inhaltlich sieht es auf /shop/ jetzt sehr bescheiden aus. Ziel war es ja mal die "normale" Suchmaske der Shop-Seite auf /shop/ nicht zu zeigen. Da die URL aber wohl von WooCommerce standardmäßig genutzt wird, mussten 2 Seiten her. Ich würde dich bitten, das nochmal rückgängig zu machen. Wäre der einfachste Weg nicht eine htaccess Weiterleitung von /shop-2018/ auf /shop/ ? Damit dürften wir doch keine Probleme bekommen oder? Schmutzig aber wirkungsvoll? ;)

**Comment by hyphone** [comment]
ok, habe in der .htaccess eine permanente Weiterleitung eingerichtet

**Comment by kellerfelix** [comment]
👍
