### ISSUE TITLE
P3 - Konfigurator: Darstellung in Rechnungs-PDFs und Bestellbestätigung etc

### ISSUE THREAD

**Issue by kellerfelix** [kellerfelix/rollladenkonfigurator#14]
Hallo Marco,

wenn ich derzeit ein konfigurierbares Produkt bestellt, kann ich sowohl im Konfigurator selbst, dem Warenkorb bis hin zum Checkout immer die Details des Produkts sehen. (Welche Farbe gewählt wurde etc).
Jedoch werden diese Details nicht in den Mails, der Bestellbestätigungsseite oder den Rechnungs-PDFs angefügt. Kannst du mir hier eine Einschätzung geben, wie lange ein Anpassung dauern würde?

**Comment by kellerfelix** [comment]
Es gibt hier unterschiedliche beteiligte Systeme. Hier aber erstmal die Punkte, die nicht funktionieren:

- Bestellbestätigungsseite / sämtliche Account-Bestelleinsichtsseiten (WooCommerce)
- Automatisch generierte versendete WooCommerce System-Emails (WooCommerce + ggf. Plugin WooCommerce Email Customizer)
- Rechnungs PDF und Liefeschein PDF (Plugin WooCommerce PDF Invoices & Packing Slips)

Das Plugin German Market ist meines Wissens nicht beteiligt. Spielt ggf. nur bei der Mwst-Sache eine Rolle.

Erstmal vertagen bis die wichtigen Sachen erledigt sind

**Comment by hyphone** [comment]
- ~~Bestellbestätigungsseite / sämtliche Account-Bestelleinsichtsseiten (WooCommerce)~~
...

**Comment by kellerfelix** [comment]
Hallo Marco,

danke für das einfügen in die Rechnungs-PDF und die automatisch versendeten System Mails. Mir ist noch aufgefallen, dass hier der  verwendet wird (Hoehe, Qm, Rbo Rollladenkasten) besser noch durch den Inhalt der Box "Titel für Konfigbox" aus dem Konfigurator ersetzt werden könnte. Lass uns das aber für nach dem Launch aufheben.

**Comment by hyphone** [comment]
Jetzt ist schick
