### ISSUE TITLE
P1 - Webseite: Haken bei "Widerrufsbelehrungen"(Checktout) funktioniert nicht korrekt

### ISSUE THREAD

**Issue by kellerfelix** [kellerfelix/rollladenkonfigurator#15]
![widerruf bug](https://user-images.githubusercontent.com/8479367/42049446-4a806672-7b06-11e8-87a9-dedfd51ba751.JPG)
Im Payment-Prozess funkioniert der Haken bei "Widerrufsbelehrungen" nicht korrekt. Ich kann hier im Schritt Bezahlungsdetails (AGB und Widerruf haken sichtbar) weiter gehen ohne einen Haken bei "Ich habe die Wiederrufsbelehrungen gelesen" zu setzen. 

Versuche ich dann allerdings zu bestellen, erhalte ich eine Fehlermeldung im letzten Schritt "Bestellübersicht": "Bitte bestätigen Sie die Hinweise zu Widerruf. 

Allerdings findet sich diese Option ja darstellungstechnisch im "Schritt" davor - Bezahlungsdetails. Bitte einen Check auf Bezahlungsdetail-Seite einbauen, damit man dort garnicht erst weiter kann ohne den Haken zu setzen. 
Hinweis: Standard-mäßig hat Woocommerce ja einen Onepager als Checkout. Um das schöner darzustellen nutzen wir das Plugin ARG Multistep Checkout für WooCommerce (http://argthemes.com/woocommerce-multistep-checkout/).

**Comment by hyphone** [comment]
Dies ist ein Fehler im Plugin German Market.
investigating...

**Comment by hyphone** [comment]
Ich schlage hier ein Update der Plugins vor. Wenn das Problem noch bestehen sollte, muss ich einen Workaround finden.
Wäre es möglich Zugang zum Server Backend zu bekommen, dann kann ich das übernehmen (Backups, Updates, usw)?

**Comment by kellerfelix** [comment]
Gern kann ich die neuste Version von German Market runterladen. Ich pack dir den Link nachher hier rein. Zugang zum Server Backend schick ich dir gleich per mail. 
Dann können wir das gerne mal ausprobieren.

**Comment by hyphone** [comment]
Das ist ein Problem zwischen Multicheckout und GermanMarket.
Wenn möglich schlage ich vor opt-in zu deaktivieren, sodass man nur einen Hinweis erhält, dass man bei Klick auf weiter dies akzeptiert und keine Checkbox explizit anklicken muss.

Einen Workaround hier zu programmieren rentiert sich nicht und würde zu viel Zeit in Anspruch nehmen, vor allem da dieser ggf. nicht updatefähig wäre.

**Comment by hyphone** [comment]
alternativer Vorschlag:

AGB und diese Checkbox vereinen, sodass nur die funktionierende aktiviert werden muss.

**Comment by hyphone** [comment]
oder das mit der Übermittlung in die AGB mit rein !?

**Comment by kellerfelix** [comment]
Find die Lösung mit der Kombination in der AGB Box super. Lassen wir so, wie sie aktuell im Shop aktiviert ist. Ich habe die Checkbox für die Datenübermittlung an das Versandunternehmen mal die Checkbox option deaktiviert. Dann gibts auch keine Fehler mehr. 
Erstmal closed!
