### ISSUE TITLE
P2 - Webseite: Checkout Texte englisch

### ISSUE THREAD

**Issue by kellerfelix** [kellerfelix/rollladenkonfigurator#16]
Wir haben im letzten Schritt des Checkouts unten noch englischen Texte. Ich habe leider keine Möglichkeit gefunden diese zu übersetzen. Kannst du hier helfen bitte?

Hinweis: Ggf. ein Standardbaustein, der vom ARG Plugin (Bestellprozess auf mehreren Schritten) überschrieben wurde.
![englische texte](https://user-images.githubusercontent.com/8479367/42049718-13e2e3b4-7b07-11e8-8a60-1aaa48308c28.JPG)

**Comment by hyphone** [comment]
Laut Doku von ARG... kommen die Texte alle von WC. Ich schlage daher auch hier erst einmal ein Update aller betreffenden Plugins vor. Besteht das Problem weiterhin können wir versuchen die Übersetzungsdateien anzupassen. Fruchtet dies nicht (und das Plugin überschreibt diese) muss ich ggf. ein neues Template erstellen.

**Comment by kellerfelix** [comment]
Du meinst also ein Update von ARG und WooCommerce? Ich denke auch dass die englischen Texte aus dem Standard-WC kommen. Ich frage mich allerdings, warum ich diese nicht übersetzen kann/diese nicht übersetzt werden.
Anyway...Prio2

**Comment by hyphone** [comment]
übersetzungsdatei für das plugin erstellt und diese 3 text-phrasen angepasst.

**Comment by kellerfelix** [comment]
Top!
