### ISSUE TITLE
P1 - Checkout: Hausnummer wird nicht übernommen

### ISSUE THREAD

**Issue by kellerfelix** [kellerfelix/rollladenkonfigurator#17]
Hi Marco,

nachdem ich gerade die Woocommerce System-Mails (Bestellbestätigung etc) optisch und inhaltlich überarbeitet habe, ist mir aufgefallen, dass die im Bestellprozess in einem Extrafeld angegebene Hausnummer nirgends weitergegeben wird.
Konkret: In Bestellbestätigungsmails, Rechnungen und auch auf der Bestellbestätigungsseite fehlt diese Info. Es steht dort nur die Straße.

Hintergrundinfos: Soweit ich mich erinnern kann hatte unser letzter Programmierer hier im Checkout ein extra-Feld für die Hausnummer eingefügt. Ich glaube standardmäßig ist in Woocommerce Straße + Hausnummer nur 1 Feld, bzw. 1 Eingabe, korrekt?
Falls das so sein sollte, lass uns entweder
a) die Hausnummer bei der Standardplatzhaltern, die weiterhin in Rechnungen und weiteren Mails verwendet werden hinzufügen [shipping_address] (wahrscheinlich komplizierter)
b) die Trennung rückgängig machen und die Hausnummern-Eingabe wieder ins Straßenfeld vornehmen.

Was meinst du? Müssten wir auf jeden Fall vor dem Live-Gang noch anpassen, da wir sonst keine richtige Lieferadresse haben 🤕

**Comment by hyphone** [comment]
Hier wurde lediglich dieser Code copy/paste eingefügt:
https://businessbloomer.com/woocommerce-add-house-number-field-checkout/

Um die Hausnummer umfangreich zu unterstützen müssten alle Templates angepasst werden wo die Adresse entspr. vorkommt (Bestellbestätigungsmails, Rechnungen, Bestellbestätigungsseite).

Lass uns das Feld für den Launch rausnehmen und ggf. später hinzufügen (Aufwand ggf. 1-2h).

**Comment by kellerfelix** [comment]
Danke, ich denke das passt auch so erstmal! Closed
