### ISSUE TITLE
P1 - Konfigurator: Fehlerdarstellung

### ISSUE THREAD

**Issue by kellerfelix** [kellerfelix/rollladenkonfigurator#2]
Problembeschreibung:

Fehlende Auswahl eines Pflichtfeldes wird nicht als rot(fehlerhaft) markiert. (getestet in Firefox & Chrome ohne Plugins). Hinweis: Nur bei Chrome werden zumindest Eingabe-Felder(!) als Rot markiert wenn keine Eingabe/Falsche Eingabe getroffen ist. Bei Radio-Buttons und Checkboxen wird aber auch hier nichts rot markiert! Das müssen wir unbedingt noch beheben!

Status: NICHT BEHOBEN

**Comment by kellerfelix** [comment]
Nach einen Update von Boris am 15.03 als behoben markiert

**Comment by kellerfelix** [comment]
Status 11.06.2018: Fehler leider immer noch vorhanden.

**Comment by hyphone** [comment]
@kellerfelix bitte checken - bei Auswahl werden die restlichen Felder der selben Kategorie nun ent-error-t

**Comment by kellerfelix** [comment]
Noch nicht ganz behoben, bzw. neuer Fehler: Bei breite/höhe Eingaben und einem Wechsel per Klick werden auch gültige Werte als rot markiert. Bei einem Wechsel mittels der TAB Taste geht es dann aber.
![bildschirmfoto 2018-06-18 um 21 55 48](https://user-images.githubusercontent.com/8479367/41558866-85cbd30e-7342-11e8-9ec6-51112a8622e5.png)

Bei Schritt 4 des Konfigurators http://wordpress.p379232.webspaceconfig.de/vorbaurolladen-konfigurator-pvc/ und KEINER Eingabe wird nur ein Teil der Pflichtfelder als fehlend markiert. Die Eingabe des Antriebsauswahl (Schalter, Motor) ist auch Pflichtfeld, wird aber nicht markiert.
![bildschirmfoto 2018-06-18 um 21 59 38](https://user-images.githubusercontent.com/8479367/41558969-ee82a242-7342-11e8-8536-a92f37acca3f.png)

Ansonsten sieht es schon sehr gut aus. Vielen Dank! Rest bitte noch beheben, wenn möglich.

**Comment by kellerfelix** [comment]
Scheint soweit behoben, danke. Allerdings ist mir noch eine Sache aufgefallen. Wenn ich bei http://wordpress.p379232.webspaceconfig.de/vorbaurolladen-konfigurator-pvc-test2/ als oberen Wert 305 eingebe (limit 300) wird es ordnungsgemäß rot markiert. Klick ich dann auf Pfeil runter geht er auf den nächsten gültigen Wert 300. Dieser bleibt jedoch rot markiert, auch wenn ich weiter runter gehe. Erst wenn ich hier wieder über die Tastatur einen gültigen Wert eintrage wechselt das Feld auf OK. Gilt scheinbar auch nur für Höhe. Bei Breite konnte ich das nicht reproduzieren.

Chrome - Win10 (Cache geleert)

**Comment by hyphone** [comment]
Schau mal ob es jetzt klappt

**Comment by kellerfelix** [comment]
Passt! Hab nichts mehr entdecken können! Endlich. Du hast das 100x schneller gelöst als unser ehemaliger Programmierer. Ich frage mich manchmal echt ob die überhaupt was gemacht haben...
