### ISSUE TITLE
P1: Anpassungen der letzten tage wiederherstellen (LISTE)

### ISSUE THREAD

**Issue by kellerfelix** [kellerfelix/rollladenkonfigurator#21]
Hallo Marco,

hier nochmal ein Überblick über die schonmal erledigten Punkte, die wieder Ihren Weg ins aktuelle Setup finden müssten:

- Checkout: Hausnummerdarstellung wieder im Extrafeld vorhanden -> beheben
- Checkout: AGB Texte wieder unter der Checkbox -> daneben darstellen
- Checkout: Englische Texte am Ende der Bestellübersicht übersetzen
- Datenschutz / DSGVO Anpassungen, die du durchgeführt hattest (Cookie notice, etc)
- /shop-2018/-Weiterleitung auf /shop/

Falls mir oder dir noch weitere Dinge einfallen, bitte ebenfalls wieder mit aufnehmen.

**Comment by hyphone** [comment]
- ~~/shop-2018/-Weiterleitung auf /shop/~~
- ~~Checkout: Englische Texte am Ende der Bestellübersicht übersetzen~~
- ~~Checkout: Hausnummerdarstellung wieder im Extrafeld vorhanden -> beheben~~
- ~~Datenschutz / DSGVO Anpassungen, die du durchgeführt hattest (Cookie notice, etc)~~
- ~~Checkout: AGB Texte wieder unter der Checkbox -> daneben darstellen~~

**Comment by kellerfelix** [comment]
Great! Ich teste das gleich noch!
