### ISSUE TITLE
P1 - Konfigurator: Preise stimmen nicht mit Tabelle überein

### ISSUE THREAD

**Issue by kellerfelix** [kellerfelix/rollladenkonfigurator#22]
Hallo Marco,

mir ist gerade aufgefallen, dass sich bei den Konfiguratoren nach Eingabe der Breite/Höhe nie die Preise aus den hochgeladenen Tabellen ergeben:

Beispiel im ALU-Panzer-Konfigurator: http://wordpress.p379232.webspaceconfig.de/rolladenpanzer-konfigurator-aluminium/

Hier ist bereits die neue Liste hinterlegt. Bei Eingabe der Maße 290x 290 ergibt sich im Konfigurator der Preis 314,19€ - in der Liste steht allerdings 372,05€. Das entspricht knapp dem Mwst Abzug von 19%.
Im Warenkorb wird das Produkt aber auch mit 314,19€ (inkl. Mwst) angezeigt und nicht mit 372,05€.

Das Problem zieht sich durch alle Konfiguratoren. Könntest du hier mal nachsehen, was da los ist? Das müssten wir dringend noch anpassen, sonst zahlt der Kunde ja zu wenig.
Hinweis: Bei der hochgeladenen Liste handelt es sich bereits um Brutto-Preise.

**Comment by hyphone** [comment]
Du hast die Datei Rolladenpanzer netto 01.11.2017 augewählt. Dort ist für 290x290 ein Preis von 314,19 hinterlegt. Scheint korrekt für mich.

**Comment by hyphone** [comment]
![bildschirmfoto von 2018-07-06 10-01-44](https://user-images.githubusercontent.com/6410852/42367186-a461504a-8103-11e8-9de8-22bd6805b9ef.png)

**Comment by kellerfelix** [comment]
perfekt - hatte meines wissens die Datei schon ausgetauscht, deshalb war ich etwas verwirrt. Naja, danke fürs prüfen.
