### ISSUE TITLE
P1 - Konfigurator: Probleme beim Anlegen einer Regel

### ISSUE THREAD

**Issue by kellerfelix** [kellerfelix/rollladenkonfigurator#23]
Hallo Marco,

ich versuche gerade noch die letzte Regel zum Vorbaurollladenkonfigurator PVC ( http://wordpress.p379232.webspaceconfig.de/wp-admin/post.php?post=1863&action=edit ) hinzuzufügen:

Regel besagt:
Wenn bei Feld "clr_Leiste" die Farbe "Anthrazit" ausgewählt wurde, darf bei der Auswahl der Rollladenkastenform "rbo_rollladenkasten" nur die Option "eckig 45 Grad" zu Verfügung stehen.

Umgesetzt habe ich das wie folgt:
![grafik](https://user-images.githubusercontent.com/8479367/42397623-f64b2756-8166-11e8-8c06-cb781c5c9466.png)

Problem: Leider scheint nur ein Werte-Kombinationsverbot ausgeblendet zu werden (Kasten viertelrund). Die ebenfalls auszublendende Option "Kasten halbrund" wird weiterhin verfügbar angezeigt. Wenn ich sie allerdings anklicke wird sie für einen winzigen Augenblick rot, lässt sih dann aber auswählen.

Ich brauche hier dringend einen Workaround. Habs schon versucht anders rum: Wenn "rbo_rollladenkasten" == eckig 45 Grad, dann ist bei "clr_Leiste" nicht die Farbe Anthrazit erlaubt. Das funktioniert zwar, allerdings wird die Farbe dann gleich zu Beginn schon deaktiviert und lässt sich nicht auswählen, obwohl noch nicht feststeht, was im nächsten Schritt gewählt werden wird.

Kannst du mir hier helfen bitte?

**Comment by hyphone** [comment]
Ich debugge zur Zeit das JS Frontend. Das ist vielleicht ein Spaghetti-Code und eine Funktion überschreibt dinge einer vorherigen...
Ich werde das jetzt notdürftig fixen. Da stehen mir wirklich die Haare zu Berge.

**Comment by kellerfelix** [comment]
Wirklich so schlimm? oh man. Vielleicht sollten wir uns nach dem Relaunch mal hinsetzen und darüber nachdenken, wie wir das Ding für die Zukunft rund machen könnten. Danke dir auf jeden Fall. Halt mich auf dem laufenden.

**Comment by hyphone** [comment]
Alright, es sollte jetzt wie gewünscht funktionieren

**Comment by kellerfelix** [comment]
Scheint zu funktionieren! Habe zur Sicherheit jetzt nochmal die anderen Konfiguratoren durchgetestet und bis auf einen scheinen alle reibungslos zu funktionieren. Problem macht der PVC Panzer mit den 2 unterschiedlichen Breite-Werten: http://wordpress.p379232.webspaceconfig.de/rolladenpanzer-konfigurator-pvc/

Problem: Wenn ich jetzt im ersten Schritt das MINI-Profil wähle (was zu einer Begrenzung auf 160cm Breite geführt hatte) kann ich jetzt auch größere Werte bei der Breite eintragen ohne Probleme mit der 160cm Begrenzung zu bekommen (keine roten Markierungen, Pfeile hoch runter führen nicht zum nächsten gültigen Wert). Ich kann auch einen Schritt weiter gehen. Ich kann das Produkt sogar bestellen.
Nur wenn ich in den ersten Schritt zurückkehre zeigt er mir das "MINI-Profil" als fehlerhafte Eingabe an und bittet mich beim Schritt-Wechsel die Auswahl anzupassen.
Das müssten wir noch beheben. Kannst du dir das nochmal anschauen bitte?

**Comment by hyphone** [comment]
Wenn ich MINI wähle und bspw. 170 bei der Breite eintrage wird das Feld rot markiert und ich komme nicht weiter.

**Comment by hyphone** [comment]
Okay, ein weiter Fehler ist behoben. Kannst du das bestätigen?

**Comment by hyphone** [comment]
Das mit "automatisch auf den nächsten gültigen Wert springen" ist eine andere Baustelle und ich müsste etwas mehr umschreiben.
Wenn du ggf. einen Hinweis einblendest, könnte es so mit wenigstens funktionierender Validierung ausreichen.

**Comment by kellerfelix** [comment]
Ok, also der Wert > 160 wird bei MINI Profil als falsch gewertet. +- -Pfeile funktionieren jetzt zwar nicht mehr (ging vorher). Hat das was mit der anderen Baustelle zu tun? Vorher hat es ja geklappt. Ist jetzt nicht so dramatisch. Ggf. baue ich hier wirklich noch einen Hinweis ein. Sollte aber erstmal funktional sein. Danke dir!

**Comment by hyphone** [comment]
Die +/ - funktionieren weiterhin (Chrome / Firefox)
Du sagtest er ging vorher nicht zum nächst gültigen Wert. Das tut er jetzt auch nicht (wie vorher), aber hoch / runter kannst du weiterhin mit + / -.
Das liegt daran, dass default max=290 ist. Dies wird nicht on-the-fly geändert und für den Browser bleibt es beim Maximalwert 290 über die + / - Icons.

**Comment by kellerfelix** [comment]
Ich danke dir :) Läuft!
