### ISSUE TITLE
P2 - Warenkorb Anzeige evtl. bugged

### ISSUE THREAD

**Issue by kellerfelix** [kellerfelix/rollladenkonfigurator#24]
Hallo Marco,

wenn ich bei mir in Chrome (Win10) in FULL-HD Auflösung ganz normal ein Produkt in den Warenkorb lege oder den Warenkorb anschaue sieht dieser bei mir so aus:

![image](https://user-images.githubusercontent.com/8479367/42447665-fb470278-837a-11e8-9d71-2a81172f37bf.png)

Problem: Wie du siehst überlappt hier die linke Liste mit der "Order-Box" rechts. Komisch ist allerdings, dass ich das weder im Chrome-Incognito-Modus sehe noch im Firefox. Dort stimmt die Darstellung. Cookies und Cache habe ich aber eigentlich alles geleert. Sieht das bei dir korrekt aus?

**Comment by hyphone** [comment]
bei mir siehts ok aus:

![bildschirmfoto von 2018-07-09 14-58-07](https://user-images.githubusercontent.com/6410852/42451805-9598a496-8388-11e8-95ed-a62d1743e5c9.png)

Kannst du mir die Zugangsdaten zu deinem Account per SMS senden, dass ich den genau gleichen Warenkorb vor mir habe?

**Comment by kellerfelix** [comment]
Ja in den anderen Browsern passt es bei mir auch. Zugangsdaten hab ich dir mal geschickt.

**Comment by hyphone** [comment]
Ok, habe die SUMME-Spalte verkleinert, die Produkte-Spalte vergrößert.
Ab sofort bricht der Warenkorb ab 1110px zur vollen Breite um.

Das Problem sollte gelöst sein.

**Comment by kellerfelix** [comment]
Super Marco! Dankesehr. Konnte den Fehler nirgends mehr finden!
