### ISSUE TITLE
P1 Konfigurator: Darstellungs-Update "Problem"

### ISSUE THREAD

**Issue by kellerfelix** [kellerfelix/rollladenkonfigurator#25]
Hi Marco,
im neusten Konfigurator ALU Vorbau ( http://wordpress.p379232.webspaceconfig.de/vorbaurolladen-konfigurator-aluminium/) gibt es leider einen Sonderfall, von dem mir vorher wieder niemand etwas erzählt hat.
Hintergrund: wir berechnen den Preis aufgrund Höhe * breite und mittels der csv-Dateien. Der Sonderfall bei ALU Vorbau ist es, dass ab einer m² Größe von 6m² produktionsbedingt keine Bestellung mehr zu den Standard-Preisen möglich ist. Daher sind in der csv-Datei nun für die entsprechenden Werte Aufpreise mit eingerechnet (Preissprung). Einzig einen Hinweis möchte ich gerne einblenden, wenn die qm >= 6 ist.

Denn ohne Hinweis an den Kunden ist das natürlich wenig sinnvoll. Derzeit habe ich es mit solchen einer Text-Meldung gelöst, die ich schon mehrfach eingebaut habe (Stichwort Hinweis Feld). Da der Hinweis nur auftauchen soll, wenn das berechnete Feld "qm" größer als 6 ist habe ich auch eine entsprechende Regel angelegt. Das funktioniert auch, allerdings nur wenn man vorab im Schritt 1 auf "Weiter" klickt und dann wieder zurück in Schritt 1 geht. Erst dann ist das Hinweis-Feld sichtbar. 
![grafik](https://user-images.githubusercontent.com/8479367/42476533-897e0c82-83ce-11e8-9ae0-5d46109ca647.png)
Das Feld:
![grafik](https://user-images.githubusercontent.com/8479367/42476604-ba93a656-83ce-11e8-94d6-be83f4af9a9a.png)
Die Regel:
![grafik](https://user-images.githubusercontent.com/8479367/42476637-d1adf45e-83ce-11e8-99ec-2c68580f20aa.png)

Leider erscheint das Feld nicht direkt nach der Eingabe des zweiten Wertes oder auch eines raustabbens. Können wir das irgendwie lösen? Dachte bisher, dass sofort bei einem Update eines Feldes / Checkmark alles neu berechnet wird.

**Comment by hyphone** [comment]
Ich kann einmal versuchen das bei Eingabe anzustoßen. Falls die Performance darunter leidet müssen wir uns etwas anderes überlegen. Schau ich mir heute Nachmittag einmal an.

**Comment by hyphone** [comment]
Wie wärs, wenn man das berechnete Quadratmeter-Feld für den Kunden zur Kontrolle einblendet (deaktiviert) und den Hinweis generell immer einblendet (Falls sie qm > ... ausgewählt haben...)?

**Comment by kellerfelix** [comment]
Outcome Gespräch:

- berechnet m² anzeigen (idealerweise links über dem Hinweis) (siehe screenshot)
![grafik](https://user-images.githubusercontent.com/8479367/42585600-5c5e195e-8536-11e8-8f10-a840d267025c.png)
- Zeiteinschätzung für sofort/im selben Schritt aufpoppende Hinweisfelder abgegeben. Wenn zeitlich fix umsetzbar, dann idealerweise nach Rücksprache umsetzen.

**Comment by hyphone** [comment]
~~berechnet m² anzeigen (idealerweise links über dem Hinweis) (siehe screenshot)~~

**Comment by kellerfelix** [comment]
Top Marco, vielen Dank! Das sieht schon ganz gut aus. Könntest du das bitte noch bündig unter die Breite packen? 

![image](https://user-images.githubusercontent.com/8479367/42637201-c73a478e-85ea-11e8-9878-0702fb7b439a.png)

Lass uns die Hinweisfelder im selben Schritt mal noch etwas nach hinten schieben. Hier würde ich gerne nochmal allgemein mit dir sprechen, wie wir die Notifications umsetzen. Da ich bei einer Änderung deinerseits gleich nochmal alle Konfiguratoren umbauen müsste, schieben wir das erstmal nach hinten, damit wir mal launchen können :)

**Comment by hyphone** [comment]
Um das alles richtig ordentlich zu machen würde es nicht beim CSS bleiben und das Markup sollte auch überdacht werden.
Das andere bisher war auch nicht wirklich schwierig, bedarf halt immer nur etwas Einarbeitungs- und Debuggingzeit.
Kümmere ich mich morgen zum frühen Nachmittag drum (vorher schaffe ich es leider nicht).

**Comment by kellerfelix** [comment]
Lass uns vielleicht vorab nochmal kurz telefonieren, damit klar ist wie das nachher aussieht. Du meinst ja sicher jetzt folgende Tasks:
- das Feld m² rot zu färben, wenn es über einen definierten Wert wie 6qm hinausgeht
- alle Eingabemasken in Schritt 1 untereinander liegen und die gleiche Breite hätten
- Bild in Schritt 1 wieder mittig

Ruf mich einfach kurz an, bevor du los legst. Ich bin erreichbar.

**Comment by hyphone** [comment]
- ~~Bild in Schritt 1 wieder mittig~~
- ~~alle Eingabemasken in Schritt 1 untereinander liegen und die gleiche Breite hätten~~

**Comment by kellerfelix** [comment]
sieht gut aus! Danke
