### ISSUE TITLE
P4 Konfigurator: Motorauswahl plötzlich verbuggt

### ISSUE THREAD

**Issue by kellerfelix** [kellerfelix/rollladenkonfigurator#26]
Hallo Marco,

mir ist gerade aufgefallen, dass sowohl beim Vorbau ALU als auch Vorbau PVC Konfigurator:
http://wordpress.p379232.webspaceconfig.de/vorbaurolladen-konfigurator-aluminium/
http://wordpress.p379232.webspaceconfig.de/vorbaurolladen-konfigurator-pvc/

die Auswahl des Motors (Feld: rbo_Gurtbedienung) seit gestern verbuggt zu sein scheint. Das hat bis gestern vor den Updates funktioniert (zumindest ist es mir nicht aufgefallen). 

Es gibt derzeit 3 Regeln, die auf dieses Feld einwirken:
Regel 1:
![grafik](https://user-images.githubusercontent.com/8479367/42531952-ab83d624-8485-11e8-85bc-88d9c3b78ee4.png)
--> Wenn Panzergewicht größer 12kg dann nur noch die beiden Motor-Optionen möglich. Panzergewicht = qm *4,5kg. 
Regel 2: 
![grafik](https://user-images.githubusercontent.com/8479367/42531958-ad3a93b8-8485-11e8-9e31-b6b4e4eb672a.png)
---> Wenn die Breite <= 69,9cm dann darf kein Funkmotor bei Feld "rbo_Gurtbedienung" gewählt werden
Regel 3:
![grafik](https://user-images.githubusercontent.com/8479367/42531962-af5282f0-8485-11e8-9b89-ee49a390764e.png)
--> Wenn Breite <= 59,9cm dann darf kein Motor bei Feld "rbo_Gurtbedienung" gewählt werden.

Problembeschreibung: 

- Wenn ich Werte unterhalb der 59,9 oder 69,9cm Breite eingebe, zeigt er das korrekte Ergebnis in Schritt 4 = Nur Gurt bzw. nur Gurt und Motor 
--> Regel 2 und 3 funktionieren
- Ab Breite 70 bietet er aber komischerweise nur noch Gurtbedienung an. Richtig wäre alle Optionen (+ Motor und +Motor Funk) anzubieten. Zumindest bis wir die Regel 1 erreichen (>12kg nur noch motoren)
- Ab 12kg (z.B. 100x 270 = 12,15kg) werden korrekt nur die Motoren angeboten.

Problem ist also der mittlere Part ab Breite 70 cm bis 12kg Panzergewicht.

Komisch ist auch folgendes:
Wenn ich im Konfigurator meine Maße anpasse und auf Weiter oder in ein anderes Feld tabbe und mich dann zu Schritt 4 durcharbeite wird mir zumindest immer eine Option angeboten. Wenn ich allerdings schon in Schritt 4 war und nachträglich meine Maße anpasse (ohne in Schritt 4 eine Auswahl getroffen habe) UND nicht mit "Weiter" oder einen Tab oder klick in ein Feld in Schritt 1 weitergehe, sondern via Klick auf den Schritt 4 oben rechts, DANN wird zwar in der Konfigbox das richtige Maß und der richtige Preis angezeigt, ABER ich kann in Schritt 4 keine der Optionen mehr wählen.

![grafik](https://user-images.githubusercontent.com/8479367/42534009-d219cc98-848b-11e8-8e71-ef196d7f9dbf.png)

**Comment by hyphone** [comment]
Ich konnte den Fehler reproduzieren, indem ich bei Breite 270 eingab, auf Tab 4 wechselte, zurück sprang und 100 bei Breite eingab.
Ich habe denke ich denk Fehler gefunden und notdürftig in der Schnelle behoben. Kannst du das bestätigen?

**Comment by hyphone** [comment]
Bei Gelegenheit und wenn Zeit zur Verfügung steht können wir darüber nachdenken die Frontend-Logik des Kombinationsverbots zu generalüberholen.

**Comment by kellerfelix** [comment]
Der Fehler scheint behoben - allerdings haben wir immer noch das Problem, dass wenn ich eine größere Breite eingebe, in Schritt 4 einen Motor wähle und dann die Breite in Schritt 1 reduziere (so dass kein Motor mehr möglich ist) - das Breitefeld einfach ohne Hinweis als rot markiert wird. Ich werde hierzu wohl noch einen Text-Hinweis einbauen müssen, der bei Motorauswahl ein Hinweisfeld einblendet. Auf Dauer sollten wir das aber anders regeln.
