### ISSUE TITLE
P3 - Shop-Urls Issue - Meinung gefragt

### ISSUE THREAD

**Issue by kellerfelix** [kellerfelix/rollladenkonfigurator#27]
Hallo Marco,

ich habe gerade festgestellt, dass an den Shop-Urls zu den Produkten etwas komisch ist:

Mittels des Plugins WUBSeo können die URls der einzelnen Produkte (inkl subkategorien. etc angepasst werden.

Eine korrekte Produkt-URL(von mir hinterlegt) lautet beispielsweise:
http://wordpress.p379232.webspaceconfig.de/bedienelemente-schalter/rollladenmotor-knebelschalter-aufputz/

Unter dieser URL wird das Produkt auch endgültig aufgerufen.

Problem: Im Shop selbst ist aber eine andere URL hinterlegt, die dann auf die obenstehende Weiterleitet:
http://wordpress.p379232.webspaceconfig.de/schalter/bedienelemente-rollladenmotorknebelschalter-aufputz-2/

Da ich eigentlich ganz gerne unnötige Weiterleitungen und doppelte Produkte etc vermeiden würde, wollte ich fragen, ob wir hier etwas dran machen können?

Hintergrund der eigenen URL:
Ich wollte dass Produkt-URLs nicht zu lang werden bei Subkategorie und sprechender werden. Daher hatte ich eine Lösung angefragt, bei der auch Subkategorie-URls angepasst werden können. Das ist aber scheinbar in WP nicht möglich, daher wurde die Lösung auf Produkt-Ebene vorgeschlagen.

Derzeit sind die Kategorien noch wie folgt hinterlegt:
.../rolladenmontage/montage-sets/
in den Produkten lauten sie aber:
/rollladenmontage-sets/[Produktname]/

Gerne würde ich die Sub-Kategorie-URls auch entsprechend anpassen.
Bin gespannt ob du eine Idee hast.

**Comment by hyphone** [comment]
Hmm, was spricht dagegen den Kategorien unter Produkte / Kategorien die gewünschte URL zuzuweisen?
Warum überhaupt das Plugin? Alle URLs können auch ohne dieses angepasst werden.
