### ISSUE TITLE
P1 - Login Seite: Hinweis für alte Kunden

### ISSUE THREAD

**Issue by kellerfelix** [kellerfelix/rollladenkonfigurator#28]
Hallo Marco,

gerne würden wir auf den Login Seiten:

https://www.mein-rollladenshop.de/mein-konto/
https://www.mein-rollladenshop.de/bezahlung/
und im Login-Layover (wenn man auf das Benutzer-Icon oben rechts klickt)

jeweils bei dem Login-Fenster einen kurzen temporären Hinweis einblenden, der alte Bestandskunden darauf hinweist dass sie sich aufgrund der neuen Datenschutzgrundverordnung leider neu registrieren müssen.

"Hinweis für Bestandskunden: Aufgrund der neuen Datenschutz-Richtlinie müssen Sie sich leider neu registrieren. Wir bitten die Umstände zu entschuldigen. Ihr Mein-Rollladenshop-Team"

Könntest du sowas einbauen? Vielleicht ähnlich dem Hinweis-Style aus dem Konfigurator?
Es haben sich schon 1-2 Leute beschwert, wäre super wenn das klappen würde.

![image](https://user-images.githubusercontent.com/8479367/43253840-2ee3b9de-90c6-11e8-83cf-53ecfcca4f3f.png)
Bitte Schriftgröße ignorieren. Standard-Größen verwenden.

**Comment by hyphone** [comment]
alright, bitte einmal checken

**Comment by hyphone** [comment]
ich habs auf die rechte seite verschoben, weil dort mehr platz war.
wenn du es lieber auf die linke habe möchtest, kein problem.

**Comment by kellerfelix** [comment]
Sieht schon ganz gut aus. Beim Login ergibt es aber mehr Sinn. Könntest du außerdem noch den Style des Konfigurators übernehmen? Also diese Grüne Box für die Hinweisfelder?
Und sag mir bitte noch kurz wo ich den Text anpassen kann, wenn du im Urlaub bist. Nur falls was sein sollte...

**Comment by hyphone** [comment]
stil habe ich angepasst.

Die Stellen zum Ändern des Textes findest du hier:

Zeile 75 in:
`/wp-content/themes/flatsome-child/woocommerce/myaccount/form-login.php`

Zeile 49 in:
`/wp-content/plugins/konfigurator/js/admin.js`

Der Grund warum es im JS ist, ist der, dass das arg-multicheckout plugin nicht die Änderungen in unserem Child-Templates nimmt und ich größere Änderungen unternehmen müsste, damit wir unsere eigenen Checkout-Templates heranziehen können. Daher der Umweg über JS.

**Comment by kellerfelix** [comment]
Hi danke dir,
könntest du den Hinweis bitte trotzdem noch zu dem Login-Part verschieben? Macht beim Registrieren keinen Sinn. Die leute scheitern beim login und brauchen dann dort die Meldung. Falls der Platz hier zuviel wird, könnten wir ja ggf. diesen Text hier entfernen und dort unsere Nachricht hinschieben? Aber bitte drauf achten, dass das auch im Layover-Login funktioniert :)
![bildschirmfoto 2018-07-26 um 20 20 34](https://user-images.githubusercontent.com/8479367/43280613-a37c2128-9111-11e8-8ef3-fa1eea2888f6.png)
