### ISSUE TITLE
P2: PayPal Express funktioniert nicht richtig

### ISSUE THREAD

**Issue by kellerfelix** [kellerfelix/rollladenkonfigurator#29]
Ich habe gerade versucht eine PayPal Express-Bestellung durchzuführen:
- Artikel in den Warenkorb gelegt
- paypal express checkout gewählt
- login in PP und Zahlungsmittelauswahl
- Weiterleitung auf Shop Bezahlungsprozess: ( https://www.mein-rollladenshop.de/bezahlung/?woo-paypal-return=true&token=EC-5BK25751LV297262M&PayerID=4HFB3KQDNADZL)

Problem ist, dass hier scheinbar Daten fehlen, um den Prozess abzuschließen. Ich habe das Plugin daher vorerst deaktiviert.

![image](https://user-images.githubusercontent.com/8479367/43257945-74ec0f7a-90d1-11e8-8eff-9af55c0327ab.png)

**Comment by hyphone** [comment]
Wo finde ich die Option PayPal Express? Ich habe nur PayPal / Lastschrift / Kreditkarte / Rechnung

**Comment by kellerfelix** [comment]
Es gibt in den woocommerce Einstellungen noch die Möglichkeit eine weitere PayPal Option zu aktivieren. Wenn diese aktiv ist wird auch wieder der gelbe Button beim Warenkorb eingeblendet. Plugin müsste ich nichts deaktivieren. Kannst es ja Mal testen. Vielleicht war das auch nur ein cookie-issue. Die Option war glaube ich unter woocommerce Einstellungen - Zahlungen

**Comment by hyphone** [comment]
Was ist der Vorteil dieser weiteren Option? Gibst du mir Test-PayPal-Daten, sodass ich das testen kann?

**Comment by kellerfelix** [comment]
PayPal Plus ist jetzt von Paypal aus für unseren Account freigeschaltet. Daher würde ich gerne nochmal einen Test damit unternehmen. Wie testen wir das am besten? (nicht live?)

**Comment by kellerfelix** [comment]
funktioniert
