### ISSUE TITLE
P1 - Konfigurator: Verschiedene Maximalwerte für Breite möglich? (FOKUS)

### ISSUE THREAD

**Issue by kellerfelix** [kellerfelix/rollladenkonfigurator#3]
Problembeschreibung:

UPDATE - Problembeschreibung hat sich geändert:
Es gibt tatsächlich das Problem mit den unterschiedlichen Breite-Maximas nur für den PVC Rollladenpanzer-Konfigurator. Dieser ist gerade noch nicht existent, basiert aber auf einer Kopie des ALU Panzer-Konfigurators.
Problem: Je nach Auswahl des MINI oder MAXI-Profils sollen unterschiedliche Maximal-Werte für die Eingabe der Breite gelten.

Ansatz: Ggf. mittels Werte-Kombinationsverbot lösbar!

OLD:
#################
Im Konfigurator (http://wordpress.p379232.webspaceconfig.de/rolladenpanzer-auf-mass-alu/ ) gelten anhand des gewählten Profils (MINI vs MAXI) verschiedene Maximalwerte für die Eingabe der Breite in Schritt 2. Mein Ansatz war es hier zwei "hoehe" und "breite"-Felder anzulegen und diese mittels Ausblenden-Regeln einzubauen:
- profil_wahl =|= MINI-Profil    ---> Darstellung des Breite-Eingabefeldes1
- profil_wahl =|= MAXI-Profil   ---> Darstellung des Breite Eingabefeldes2

Dies scheiterte jedoch scheinbar an den Regeln: Sobald auch nur eine solche UNGLEICH-Regel hinterlegt wird, hatte ich im Frontend wieder den gesamten Konfigurator-Inhalt auf einer Seite dargestellt - ohne Möglichkeit der Interaktion und dunkelgrau hinterlegt. Sobald ich die Regel entferne oder >, <, >= , >= nutze, lässt sich der Konfigurator im Frontend wieder nutzen. 

Das Problem hatten wir ja schon einmal. Damals lag es daran, dass überhaupt keine Regeln hinterlegt waren. 

**Wichtigste Frage zuerst:** Eigentlich müsste diese Ausblende-Regeln doch funktionieren? Ich habe etwas ähnliches ja bereits im anderen PVC Vorbau Konfigurator in Schritt 3 gelöst. Hier wird je nach Auswahl der Kastenform ein anderer Schritt für die Auswahl der Einbauart genutzt. Dort klappt es ja bereits. Warum hier nicht?

- Frage dazu: Kann ich zwei Felder mit demselben Datenbanknamen (hoehe, bzw breite) hinterlegen? Diese benötige ich ja für die Berechnung des Preises aus der Tabelle? Wenn eines davon ausgeblendet wird, kann dann das sichtbare für die Berechnung dienen. Falls das nicht geht, brauchen wir hier dringend eine ander Möglichkeit! 

- Die Werte die für die Tabelle benutzt werden, müssen genauso auch in der Datei heißen oder?  Es ist also nicht möglich "breite2" zusätzlich als Feld zu definieren und aus der Datei auszulesen?

**Alternative Lösung 1**: Falls wir zu 53) keine schnelle Lösung finden, muss eben vorerst noch ein entsprechender Warnhinweis als Workaround dienen. Dazu wäre es interessant zu wissen, ob es eine Möglichkeit gibt eine Ausblenden-Regel so zu nutzen/zu erweitern, dass hier zwei Werte den Vorgaben entsprechen müssen, um ein Feld auszublenden: 

A) Profil = MINI --> Texthinweis "breite >160cm"
B) Profil = MAXI --> Texthinweis "Breite >120cm"

Beide Warnhinweise können ja zunächst versteckt sein und nur dann aktiviert werden, wenn eine Auswahl erfolgt ist oder? 

**Alternative 2:** Könnte man das ggf. kurzfristig nachrüsten, falls nicht möglich? Bitte eine kurze Einschätzung abgeben bevor daran gearbeitet wird.

**Comment by kellerfelix** [comment]
Update vom Gespräch gerade:
- Gleiche Feldernamen sind verboten
- felder müssen immer breite, hoehe heißen

Alternative 2: Eigenen Konfigurator für Mini / MAXI Profile bauen

**Comment by kellerfelix** [comment]
Status 11.06.2018: Immer noch Lösung. Wie könnte denn eine Lösung für ein berechnetes Feld aussehen? Ich hab das ja versucht, bin aber gescheitert (siehe oben). Bitte idealerweise eine Kopie des Konfigurators anlegen und dort exemplarisch lösen wenn möglich.

**Comment by kellerfelix** [comment]
Ggf in Verbindung mit der Lösung von 53B) einfacher lösbar. Wenn wir erst 53B) fixxen, dann den Ablauf des ALU Konfigurators dann anpassen (zuerst Breite, dann MINI/MAXI Auswahl), dann sollte es doch wiederrum möglich sein, eine der Optionen (MINI/MAXI) anhand der eingegeben Breite und einem Werte-Kombinationsverbot zu verbieten, oder? Dann wäre die Eingabe der Breite relativ egal und wir nehmen einfach den größten, bzw. kleinsten Wert als Limit für das Breite-Feld und legen entsprechende Regeln an, die dann beispielsweise MINI/MAXI Option sperren, wenn die Breite > oder < als X ist. Funktioniert das oder bin ich jetzt etwas wirr geworden? Das klingt für mich sogar dann recht einfach dann. Was meinst du dazu?

**Comment by hyphone** [comment]
Vorschlag:

- Bei Felder wird der Standard-Wert eingegeben.
- Bei Regeln könnte ich eine neue Regelart erstellen, die bspw. "neuer Max-Wert"
   - dort könnte man, ähnlich wie beim Kombinationsverbot beschreiben, wenn FeldX Wert XX hat, soll Feld Y einen neuen Maximalwert erhalten

**Comment by kellerfelix** [comment]
Hi Marco,
dein Vorschlag klingt auch gut, aber könnten wir das Problem denn nicht trotzdem mit den bereits vorhandene Bordmitteln bzw. deinem Fix von 53B) und dem oben beschriebenen Vorgehen umgehen?
Dank dir schonmal für die Antwort!

**Comment by hyphone** [comment]
Hi Felix,

es sollte auch mit dem Kombi-Werteverbot funktionieren, schau mal hier:
http://wordpress.p379232.webspaceconfig.de/wp-admin/post.php?post=1902&action=edit

Die Regeln habe ich entsprechend angelegt und greifen. Hier reicht dann ggf. ein Hinweis-Feld im 2. Schritt.

Was denkst du?

**Comment by kellerfelix** [comment]
Seh ich mir an...

**Comment by kellerfelix** [comment]
Problembeschreibung hat sich nochmal etwas angepasst. Sollte aber jetzt mit deiner Lösung machbar sein. Ich teste das gleich nochmal mit dem neuen Konfigurator: http://wordpress.p379232.webspaceconfig.de/rolladenpanzer-konfigurator-pvc/

Folgendes Testergebnis:
- Wenn ich MINI-Profil auswähle (Breite muss dann kleiner gleich 160 sein) wird mir im nächsten Schritt die Breite bereits als rot markiertes Feld angezeigt. 
- Gebe ich 160 eingebe wird das Feld wieder korrekt angezeigt.
- Wenn ich einen Wert größer 160 eingebe, z.B. 190 und dann mit dem - Button den Wert verringere, springt die Angabe nicht wie bei den anderen Konfiguratoren durch die Maximalwerte vorgesehen auf den nächsten gültigen Wert.

--> Todos:
- Fehlerkennzeichnung zu Beginn verhindern
- (Wenn zu größer Wert eingegeben wird, über die Kleiner-Pfeil-Schaltfläche den nächsten gültigen Wert bestimmen lassen.)

Letzteres ist vermutlich etwas aufwendiger...sag mir Bescheid, ob es das ist, dann würde ich das eher für später ins Auge fassen wollen.

**Comment by kellerfelix** [comment]
Kurzes Update dazu: Habe noch den Text-Hinweis unter den Breite-Feldern ausgetauscht. Auch die Regeln für gegenseitiges Text-Feld ausblenden funktionieren! Komischerweise habe ich seit dem auch keine rote Fehlermeldung des Eingabefeldes Breite nach der Auswahl Mini. Scheint also behoben? Kannst du das bestätigen?

**Comment by hyphone** [comment]
Sieht für mich gut aus.
Wähle MIN aus, Werte eingegeben, Validierung ok
gehe zurück und wähle MAX aus, gebe wert > 160 ein, Validierung ok
gehe zurück und MIN ist deaktiviert
gehe zu Schritt 2 und ändere Wert auf < 160
gehe zurück und MIN wieder aktivierbar

Müsste nur noch ein Hinweis ggf. zur Erklärung hin.

**Comment by kellerfelix** [comment]
Guter Hinweis, das könnte ich in Schritt 1 noch einbauen! Danke für den Hinweis!
