### ISSUE TITLE
P1 Paypal Error 500

### ISSUE THREAD

**Issue by kellerfelix** [kellerfelix/rollladenkonfigurator#30]
Hallo marco,

hab gerade mal den normalen Bestellprozess durchgespielt mit Paypal und dabei bin ich nach dem Kauf auf Paypal weitergeleitet worden. Anschließend hab ich auch hier wieder mein Zahlungsmittel ausgewählt und bin hier gelandet:
![image](https://user-images.githubusercontent.com/8479367/43258219-6317b19a-90d2-11e8-8b2d-41d535d59bbe.png)

Kannst du das bitte schnellstmöglich kontrollieren und ggf. abstellen?

https://www.mein-rollladenshop.de/wc-api/Woo_Paypal_Plus_Gateway/?paymentId=PAY-84749754536074210LNM2NNA&token=EC-0C5279699X611602R&PayerID=4HFB3KQDNADZL

**Comment by kellerfelix** [comment]
![image](https://user-images.githubusercontent.com/8479367/43258301-a1fd0aae-90d2-11e8-9cba-200adf71c94a.png)

**Comment by kellerfelix** [comment]
Update: Ok, im incognito modus hat es funktioniert - wierd

**Comment by kellerfelix** [comment]
Eventuell hat das wieder was mit caching zu tun. Auf meinem derzeitigen Browser hat es jetzt auch ohne incognito nochmal geklappt. Allerdings habe ich eine Bestellung zuvor während des PayPal Zahlungsprozesses abgebrochen. Ich war also noch in PayPal eingeloggt. Evtl hat das damit zu tun.

**Comment by hyphone** [comment]
Versuche es noch einmal. Ich habe wc-api als Ausnahme zum Page-Cache hinzugefügt. Bei mir schauts erstmal gut aus.

**Comment by kellerfelix** [comment]
Ist auch nach deiner Ausnahme noch vorgekommen. Nach deaktivieren des Cachings nicht mehr vorgekommen. Wollen wir alternativ zu dem W3C mal noch WP Rocket ausprobieren? Das ist wohl von Haus aus schon für WooCommerce vorkonfiguriert und man braucht nichts weiter einzustellen. Eine aktuelle Lizenz dafür hätte ich vorliegen.
Was meinst du?
