### ISSUE TITLE
P1 : Mails landen teilweise im Spam

### ISSUE THREAD

**Issue by kellerfelix** [kellerfelix/rollladenkonfigurator#31]
Hallo marco,

nur als Reminder: Wir wollen die Zustellbarkeit verbessern. Dazu werden wir alle Maßnahmen nutzen, die über Hetzner möglich sind. DKIM etc.

ich kümmer mich erstmal darum

**Comment by kellerfelix** [comment]
DKIM und dergleichen sind für den Server bereits aktiviert. Gibt es noch weitere Möglichkeiten die Zustellrate zu vergrößern? Würde ungern auf einen externen Mail-Versand Provider wie Newsletter2Go zurückgreifen. Das bedeutet nur eine Fehlerquelle mehr.

**Comment by hyphone** [comment]
Was stimmt mit der Zustellbarkeit der mit Hetzner versendeten Mails nicht?

**Comment by kellerfelix** [comment]
Scheinbar läuft alles über einen Server und der wird auch für SPAM genutzt. Das wiederrum zieht die Reputation aller dort versendeten Mails herunter. Einzige Lösung: Eine eigene IP für den Versand (nicht geshared mit anderen). Weiß nicht genau wie die Struktur dort aussieht, aber ich bekomme fast alle meine Mails bei Gmail so: 
![image](https://user-images.githubusercontent.com/8479367/44397366-67a29b80-a540-11e8-8090-f0ea32e7d315.png)

**Comment by hyphone** [comment]
Ich setze mich mit Hetzner in Verbindung

**Comment by kellerfelix** [comment]
Gab wohl auch bei Kunden das Problem. Manchmal gehen die durch und oftmals nicht. Eigentlich müssten wir mit einer eigenen IP ja auch eine eigene Reputation haben. DMARC+DKIM und SenderID sollten ja bereits aktiv sein. Bin gespannt was bei deinem Gespräch rauskommt.

**Comment by kellerfelix** [comment]
Hallo Marco,
in letzter Zeit treffen wieder verstärkt Beschwerden ein, dass Mails nicht ankommen. Speziell die Registrierungsmails. Transaktionsmails scheinen aber durchzukommen. Könntest du dir das bitte nochmal ansehen?
![aktivierungsmail spam](https://user-images.githubusercontent.com/8479367/47779500-85873c00-dcf9-11e8-9ff4-362306fdfff1.PNG)
