### ISSUE TITLE
P1 Konfigurator: "Titel" für Konfigbox defekt

### ISSUE THREAD

**Issue by kellerfelix** [kellerfelix/rollladenkonfigurator#32]
Hallo Marco,

ich habe gerade bemerkt, dass im Warenkorb bei den Details der Konfiguratoren die falschen Texte angezeigt werden. Im Konfigurator haben wir bei jedem Feld eine Option "Titel für die Konfigbox". Diese funktioniert im Konfigurator auch super, im Warenkorb allerdings noch nicht. Hier wird immer nur der Feld-Titel benutzt. Das führt dazu, dass hier teilweise ganze Sätze stehen:

![bildschirmfoto 2018-07-29 um 12 54 42](https://user-images.githubusercontent.com/8479367/43365577-3c84ac72-932f-11e8-9161-5f5111db3295.png)

Bei Gelegenheit bitte anpassen

**Comment by hyphone** [comment]
> Im Konfigurator haben wir bei jedem Feld eine Option "Titel für die Konfigbox". Diese funktioniert im Konfigurator auch super, im Warenkorb allerdings noch nicht. Hier wird immer nur der Feld-Titel benutzt.

Nicht immer. Wenn bspw. kein "Titel für die Konfigbox" gesetzt ist, wird der Feld-Titel genutzt.
Ich habe diese Abfrage entfernt. Ab sofort wird nur "Titel für die Konfigbox" ausgegeben, wenn gesetzt. Ansonsten nur der Wert des Feldes.

**Comment by hyphone** [comment]
Ab sofort werden die Feld-Namen (rbo_xyz) nicht mehr ausgegeben.

**Comment by kellerfelix** [comment]
Werde ich mal testen. 

Beste Grüße,
Felix

**Comment by hyphone** [comment]
Kann dies geschlossen werden?
