### ISSUE TITLE
P2 - Konfigurator Fehlende Elemente in Bestellbestätigung

### ISSUE THREAD

**Issue by kellerfelix** [kellerfelix/rollladenkonfigurator#38]
Hi Marco,

wenn ich einen PVC Vorbau-Konfigurator ausführe, dann erscheint in meiner Übersicht rechts korrekt der **1-Kanal Handsender**. Im Warenkorb finden sich ebenfalls alle Details, aber in der Bestellbestätigung, den Bestellbestätigungsmails, der Rechnung etc fehlt diese Option aber komplett. Bzw wird nicht angezeigt. Damit weiß der Kunde nicht ob er das mitbestellt hat oder nicht. Im Backend können wir das sehen, der Kunde aber eben nicht.

Edit: Betrifft auch: 
- Angabe Maxi oder Mini Profil
- Insektenschutz und die Hochschiebesicherung 

Übersicht:
Konfigurator: Option wird angezeigt
Warenkorb: Option wird angezeigt
Checkout: Fehlt
Bestellbestätigungsseite: Fehlt
Bestellbestätigungsmails: Fehlt
Rechnung: Fehlt

Konfigurator:
![handsender_bug_konfigurator_vorhaben](https://user-images.githubusercontent.com/8479367/47782284-27118c00-dd00-11e8-88ad-a9c84722695d.PNG)
Bestellbestätigung:
![handsender_bug_bestellbestatigung_vorhaben](https://user-images.githubusercontent.com/8479367/47782325-3ee91000-dd00-11e8-9c1a-7bed8dafe722.PNG)
Bestellbestätigungsmails:
![handsender_bug_bestellbestatigungsmail_vorhaben](https://user-images.githubusercontent.com/8479367/47782334-47414b00-dd00-11e8-930a-48d2436122fd.PNG)
Rechnung:
![handsender_bug_rechnung_missing](https://user-images.githubusercontent.com/8479367/47782353-4f00ef80-dd00-11e8-8468-e54272e18b55.PNG)

**Comment by hyphone** [comment]
Sind dort die Felder "Titel für Konfigbox" gefüllt?

**Comment by kellerfelix** [comment]
Wenn ich das soweit richtig gesehen habe, fehlen die überall *facepalm*

Ich spiel nochmal ne Bestellung durch um das Ergebnis zu testen. Sieht aber gut aus.
