### ISSUE TITLE
P2 - PayPal Checkout Button hovert über allem

### ISSUE THREAD

**Issue by kellerfelix** [kellerfelix/rollladenkonfigurator#39]
Gerade ist mit aufgefallen, dass der gelbe Checkout Button auf den Produktseiten beim runterscrollen auch über das Menü und die Top-Navi drüber läuft. Kannst du das bitte beheben?

https://www.mein-rollladenshop.de/rollladenmontage-maxi-system/halterung-fuer-kugellager/

![image](https://user-images.githubusercontent.com/8479367/48058605-2329b200-e1b7-11e8-9b15-11a62c7f43bf.png)

**Comment by hyphone** [comment]
ist nun behoben

**Comment by kellerfelix** [comment]
fixxed. bitte auch auf live spielen :)

**Comment by hyphone** [comment]
Ich kopiere erst auf live, wenn der Rest auch abgesegnet ist
