### ISSUE TITLE
P1 - Konfigurator: Motorbreite - Werte-Kombinationsverbot (JavaScript fix fehlt noch)

### ISSUE THREAD

**Issue by kellerfelix** [kellerfelix/rollladenkonfigurator#4]
Problembeschreibung:

Ich möchte eine Werte-Kombinations Verbot in Schritt 4 http://wordpress.p379232.webspaceconfig.de/vorbaurolladen-konfigurator-pvc/  einrichten (siehe Screenshot).  ![53](https://user-images.githubusercontent.com/8479367/40254312-30e3663a-5ae3-11e8-8d0f-abffcc56f129.JPG)
Ziel soll es sein ein Verbot einzurichten, dass es unmöglich macht einen Motor in Schritt 4 mitzubestellen/auszuwählen, falls das konfigurierte Produkte eine Breite kleiner 60cm (Motorbedienung Taster) bzw. 70cm (Motorbedienung Funk) hat.

Ich habe dazu bereits versucht eine Lösung einzubauen. Der Wert motorbreite wird hierbei berechnet (siehe screen 2).
![53b2](https://user-images.githubusercontent.com/8479367/40254385-758994e4-5ae3-11e8-874e-3348a3472117.JPG)

Leider greift das Verbot aber nicht. Habe ich hier einen Denkfehler? Muss der Multiplikator angepasst werden? Bin ratlos und habe schon einiges ausprobiert inzwischen.

**Comment by betzholz** [comment]
Generell gibt es das Problem, dass zwei Regeln auf das selbe Feld ein Konkurenzproblem haben. Da Regel nacheinander Ausgeführt werden. Kann nur ich nicht gleichzeitig die Regeln validieren. 
Das Thema haben wir immer wieder... Sorry wenn das jetzt hart klingt. Aber der Umbau davon wäre recht groß und wenn es dir darum geht an den Start zu kommen. Kann ich das nicht zeitnahe umsetzten. Zumal es nicht mit dem Anfangsspezifikationen übereinkommt.

**Comment by kellerfelix** [comment]
Hallo Boris,
das mit den zwei Regeln auf ein Feld hattest du bereits gesagt, ja. Wäre es hier dann aber nicht zumindest möglich auf oben beschriebene Art und Weise wenigstens ein Kombinations-Verbot zu hinterlegen?
Ansonsten müssen wir das eben mit zwei versteckten Hinweis-Feld regeln, dass bei entsprechenden Auswahl der Breite dann den Hinweis anzeigt. Das sollte doch funktionieren oder?

**Comment by kellerfelix** [comment]
Status 11.06.2018: Immer noch keine Lösung in Sicht. Für den Start muss wohl ein Hinweis-Feld herhalten. Wir brauchen hier aber trotzdem langfristig eine Lösung! Bitte sag mir, wie so etwas aussehen könnte! Danke :)

**Comment by hyphone** [comment]
Position Feld einfügen (Prio)

**Comment by hyphone** [comment]
Möglichkeit für Mehrfachbedingung einer Regel eingefügt (es lassen sich nun mehrere Radiobuttons mit eienr Regel deaktivieren)

nächster Schritt:
mehrere Regeln berücksichtigen

**Comment by hyphone** [comment]
Es fehlt nun noch folgende Funktionalität:
- Breite 70 eingeben
- Motor wählen
- Breite ändern auf 50
- Motor bleibt gewählt obwohl deaktiviert (sollte wieder auf Default, nichts ausgewählt springen)

**Comment by kellerfelix** [comment]
Hiho,

also im Testprodukt funktioniert das jetzt astrein. Musste die Maße allerdings an 69.9 und 59.9 anpassen, damit es ab 70/60 möglich ist. Vielen Dank!!!

**Bug**: aus irgendeinem Grund sieht der PVC Original Konfigurator (http://wordpress.p379232.webspaceconfig.de/vorbaurolladen-konfigurator-pvc/)  jetzt so aus. Alles wird auf einer Seite dargestellt, ist von einem graune Kasten überlagert und lässt sich nicht aktivieren:
![image](https://user-images.githubusercontent.com/8479367/41777580-19a6f9d2-762c-11e8-99bf-6573ab165e3e.png)

Bei der Kopie von dir (http://wordpress.p379232.webspaceconfig.de/vorbaurolladen-konfigurator-pvc-test2/ ) ist das nicht so. Woran liegt das?
**Hinweis dazu:** Der Fehler ist in der Vergangenheit bei Änderungen am Konfigurator häufiger aufgetaucht.  Woran es allerdings lag kann ich nicht erklären, das wurde mir nie mitgeteilt. Cache wurde geleert und Browser gewechselt (Chrome/FF - Win10).

Ansonsten soweit closed!

**Comment by kellerfelix** [comment]
Hier steht nur noch die Beseitigung des JavaScript Fehler aus. 👍

**Comment by hyphone** [comment]
ok, ist drin

**Comment by kellerfelix** [comment]
tested. Dank dir!
