### ISSUE TITLE
P1 - Konfigurator braucht ein Message-Fenster

### ISSUE THREAD

**Issue by kellerfelix** [kellerfelix/rollladenkonfigurator#41]
Hallo Marco,

beim alten Konfigrator hatten wir ein Nachrichten-Feld am Ende des Konfigurator-Prozesses eingebaut, bei dem die Kunden nochmal eine Nachricht hinterlegen konnten. Können wir sowas hier auch noch einbauen?
Vielleicht einfach als eigenes Feld? Ist wahrscheinlich die einfachste Lösung.
Folgende Anforderungen:
- Textfeld für standard eingabe (abgesichert gegen DB-Expoits)
- Textfeld kann genutzt werden, muss aber nicht
- Standardhöhe Feld (2 Zeilen)
- Textnachricht sollte wie die anderen Optionen auch an die Konfigrator-Details gehängt werden.
- ggf. Textlimit falls nötig.

Nach Möglichkeit bitte zeitnah einbauen.

Vielen Dank.

**Comment by hyphone** [comment]
Bitte mal in diesem Produkt prüfen:
https://staging.mein-rollladenshop.de/wp-admin/post.php?post=2042&action=edit

Hinweis: wie bei allen Feldern muss "Titel für Konfigbox" gefüllt sein, damit es beim Checkout und der Rechnung auftaucht.

**Comment by kellerfelix** [comment]
Optisch sieht das auf jeden Fall gut aus. Konnte aufgrund der Fehler leider nicht schauen, wie das im Warenkorb dann aussieht.
Der Titel für Konfigbox ist ok :) Bin gespannt wie es aussieht wenn du fertig bist.

**Comment by hyphone** [comment]
Teste kannst du es jetzt. Es gab ein Fehler im upgedateten Theme. Ich musste zur Live-Version des Themes zurück wechseln.

Das neue Feld, was zur Auswahl steht, nennt sich "Eingabe (mehrzeilig)". Wir können dies auch etwas anders stylen, dass es mehr hervorsticht. Zusätzlich könnte man die Aufmerksamkeit mit einem Hinweis-Feld erzeugen.

**Comment by kellerfelix** [comment]
Super, schau ich mir an! 
Die Idee mit dem Hinweis davor finde ich gut. Ich mache mir zum Styling nochmal Gedanken. Danke dir schonmal :)

**Comment by kellerfelix** [comment]
Sieht soweit gut aus. Allerdings ist mir bei dem Konfigurator aufgefallen, dass auf der ersten Seite jetzt immer der Warnmodus anspringt für das Eingabefeld der Breite. Und das gleich beim Start. Hängt das damit zusammen?

Außerdem ist mir auf der Bestellbestätigungsseite (bsp: https://staging.mein-rollladenshop.de/bezahlung/order-received/2709/?key=wc_order_5bfd0771cc63e) aufgefallen, dass die Texte komisch umbrechen:
![image](https://user-images.githubusercontent.com/8479367/49070147-45997300-f22b-11e8-9c4d-7b8b4dffab41.png). Hier sollte noch alles untereinander stehen.
In der Darstellung auf der Rechnung passt es:
![image](https://user-images.githubusercontent.com/8479367/49070308-a1fc9280-f22b-11e8-9d69-c8e2bbef8786.png)

**Comment by hyphone** [comment]
- Fehler mit error-markiertem Breite-Feld gefunden und beseitigt
- Umbrüche sehen nun besser aus

**Comment by kellerfelix** [comment]
Funktioniert
