### ISSUE TITLE
P3 Java Script Errors fixxen

### ISSUE THREAD

**Issue by kellerfelix** [kellerfelix/rollladenkonfigurator#43]
Hi Marco,

hatte vor einer Weile in GTM einen Tag eingerichtet, der mir ausgespielte JAVA Script error Meldungen als Event in GA einspielt. Das sind relativ viele (750 in 1 Woche). Wahrscheinlich nichts dramatisches. Trotzdem wäre es super, wenn du das mal überpürfen könntest.

Diese Infos habe ich:
![image](https://user-images.githubusercontent.com/8479367/48984744-03bfde00-f100-11e8-9e87-21fda05013da.png)

Zu Error 2:
![image](https://user-images.githubusercontent.com/8479367/48984752-1afecb80-f100-11e8-908a-b747c5feac26.png)

Vermutlich alles nichts dramatisches. Aber langfristig würde ich die Seite doch gerne schon komplett rund bekommen :)

PS: Derzeit sind javascripte noch nicht minified oder zusammengelegt (Caching).

**Comment by hyphone** [comment]
Zu Fehler 1 fehlen mir mehr Informationen.

Fehler 2 kann ich sehen und hängt mit dem PayPal Plugin zusammen (es erwartet bspw. im Konfigurator direkt den PayPal Button und findet ihn nicht - das ist der Fehler hier).

Fehler 4 und 5 sind lange gefixt, wenn ich mich recht entsinne - vielleicht hast du hier mehr Infos für mich.

**Comment by kellerfelix** [comment]
Alles klar. Kannst du denn im Browser irgendwelche Fehler in der Konsole ausmachen?

Denke das meiste wird harmlos sein. Hab mich nur gewundert.

Ich schau mich nochmal um und aktualisier dann den Beitrag hier.

**Comment by hyphone** [comment]
Siehe oben ;)
