### ISSUE TITLE
P1 - Update-Time

### ISSUE THREAD

**Issue by kellerfelix** [kellerfelix/rollladenkonfigurator#49]
Hi Marco,

ich möchte gerne unsere Installation wieder auf den neusten Stand bringen. Dazu gehört:

- Update aufs neue Wordpress
- Update auf das neue Woocommerce
- Flatsome-Theme Update auf 3.10 (DL-Link: https://www.dropbox.com/s/1sco4gu40ymyjzl/flatsome-3.10%20-%20theme2.zip?dl=0 )

Zusätzlich würde ich auch gerne ein paar der Plugins updaten. Das meiste davon sollte zu keinen Problemen führen. Ggf. kann ich dies auch durchführen. Bitte gib mir dazu vorweg eine kurze Einschätzung.
- Contact Form 7
- Google Tag Manager for Wordpress
- SV ProvenExpert (unsere Bewertungs-Widgets)
- WooCommerce PayPal Checkout Gateway
- WooCommerce PDF Invoices & Packing Slips
- WP Migrate DB (Wird das überhaupt noch gebraucht?)
- WP Rocket (Caching)
- Yoast SEO Premium (File unter: https://www.dropbox.com/s/3eqo4oej45ufe5a/wordpress-seo-premium%2012.9.2.zip?dl=0 )
- Yoast NEWS Premium ( File unter: https://www.dropbox.com/s/4ogmn4b7xfw2tme/Yoast%20seo-news%2012.4.1.zip?dl=0 )
- Yoast Video SEO ( File unter: https://www.dropbox.com/s/3c2dw961z6ft5fg/Yoast%20Video%20seo%2012.4.zip?dl=0 )
- Yoast SEO Woocommerce (File unter: https://www.dropbox.com/s/cqcfvf25m38o83a/Yoast%20SEO%20woocommerce%2012.4.1.zip?dl=0 )
- WooCommerce Email Customizer with Drag and Drop Email Builder ( File unter: https://www.dropbox.com/s/nwzy67iow10rb77/woocommerce-email-customizer-with-drag-and-drop-email-builder-1.5.0.zip?dl=0 )
- German Market ( File unter: [uploading] )

Bitte gib mir dazu vorweg eine Einschätzung :)

**Comment by hyphone** [comment]
done auf Staging

**Comment by kellerfelix** [comment]
https://www.dropbox.com/s/8bpql24mjter6uu/woocommerce-german-market%203.9.1.zip?dl=0
@hyphone :)

**Comment by kellerfelix** [comment]
Hier ein kurze Liste der noch entdeckten Bugs:

1. Im Flyout-Warenkorb ist der Konfigurator-Inhalt plötzlich sehr weit auseinander gezogen dargestellt:
![image](https://user-images.githubusercontent.com/8479367/74049042-9b42e100-49d3-11ea-9396-34d295af0b1e.png)
Aktion: Bitte wie im Entwurf für den Checkout darstellen:
![image](https://user-images.githubusercontent.com/8479367/74049099-be6d9080-49d3-11ea-84fe-df0a4c426c29.png)

2. Ebenfalls im Flyout-Warenkorb: Die Paypal-Quick Express Checkout Option fehlt: Vgl:
![image](https://user-images.githubusercontent.com/8479367/74049207-efe65c00-49d3-11ea-83fd-7ecee364ecfc.png)
Aktion: Falls nicht aktiviert, bitte wieder aktivieren

3. Checkout betreffendes: Siehe Checkout Issue

to be continued...
