### ISSUE TITLE
P2 - Konfigurator: Abstände und Bildgrößen variieren

### ISSUE THREAD

**Issue by kellerfelix** [kellerfelix/rollladenkonfigurator#5]
Problembeschreibung:
Die Abstände und Bildgrößen (Breite) variieren bei dem Radio-Buttons mit Bildern scheinbar (siehe screenshot) nach einem Umbruch. Kannst du das bitte mit anpassen?
Produktlink: http://wordpress.p379232.webspaceconfig.de/rolladenpanzer-konfigurator-aluminium/

**Comment by kellerfelix** [comment]
Boris am 15.03: Status Behoben

**Comment by kellerfelix** [comment]
Neues Problem nach dem Update: 
Farbtexte brechen jetzt scheinbar komisch um und verschieben die Option in der Höhe. Das war vorher nicht der Fall.
![54](https://user-images.githubusercontent.com/8479367/40254535-1be0ef2c-5ae4-11e8-991c-6e7cef793e18.JPG)

**Comment by kellerfelix** [comment]
Status 11.06.2018: Problem immer noch vorhanden

**Comment by hyphone** [comment]
@kellerfelix bitte prüfen, sollte nun ok aussehen

**Comment by kellerfelix** [comment]
Gerade auf dem Laptop (MacOS - Chrome) getestet. Einige Fehler behoben (Versatz). Abstände sind bei mir allerdings immer noch unterschiedlich. Siehe Screenshots. Auch beim anderen Konfigurator (Schritt 2): http://wordpress.p379232.webspaceconfig.de/vorbaurolladen-konfigurator-pvc/

![bildschirmfoto 2018-06-18 um 21 45 55](https://user-images.githubusercontent.com/8479367/41558495-4b7e296e-7341-11e8-9927-eb20390274bf.png)
![bildschirmfoto 2018-06-18 um 21 44 12](https://user-images.githubusercontent.com/8479367/41558496-4bb11a36-7341-11e8-80ef-399ffef4d9ac.png)

Liegt das ggf. an der Länge des Textes darunter?

**Comment by hyphone** [comment]
Ok ich ging davon aus, dass die Höhe nur angepasst werden soll.
Möchtest du, dass die Spalten alle gleich breit sind?

**Comment by kellerfelix** [comment]
Ah, alles klar. Die Höhe passt jetzt überall.
Ja idealerweise sollten sich die vorhanden Elemente in der Breite gleichmäßig aufteilen. Also nicht je nach Elementinhalt eine Breite zugewiesen bekommen (siehe Textlänge in Screenshots oben).
Umbrüche bei zu vielen Elementen soll natürlich weiterhin möglich sein. Müssen wir hier eine Anzahl definieren? Ich möchte auch nicht, dass beispielsweise die Farbfelder ("Wählen sie die Farbe der Endleiste") dann aber in der Höhe größer werden. Aber das sollte ja kein problem sein.

**Comment by kellerfelix** [comment]
Update: Die gleichen Abstände sind noch nicht hergestellt.

**Comment by kellerfelix** [comment]
Super, passt!
