### ISSUE TITLE
P1 - Kategorie-Update vorbereiten

### ISSUE THREAD

**Issue by kellerfelix** [kellerfelix/rollladenkonfigurator#52]
Hallo Marco,

wir arbeiten gerade daran unsere Kategorisierung im Shop etwas detaillierter und umfassender aufzubauen. Dazu gehört die Schaffung neuer Kategorien, der Schaffung einer neuen URL-Struktur etc.
Gerne würde ich dazu noch eine **Umgestaltung der Kategorie-Seiten** vornehmen. Wahrscheinlich lässt sich das mit den Bord-Mitteln des Flatsome-Themes lösen, aber ich würde mich über eine Einschätzung deinerseits sehr freuen. Hier meine Vorstellungen:

Es soll in Zukunft 2 verschiedene "Designs" für Kategorie-Seiten geben: 

- Hauptnavigations-Punkte (Kategorien erster Ebene)
- Subkategorien (Kategorien der tieferen Ebenen)

(Evtl kann man diese ja mittels der Kategorie-Texten, Blocks aus dem Theme selbst umsetzen)

Hauptnavigations-Kategorien sollen:
- an oberster Stelle eine Auswahl-Navigation über die verfügbaren Unterpunkte enthalten. Vgl. hier:
![image](https://user-images.githubusercontent.com/8479367/73254213-41197300-41be-11ea-941f-457399980d03.png) Oder direkt auf: https://www.jalousiescout.de/Gurtwickler
- Darunter soll es möglich sein einen umfangreichen umfangreiche Texte und Seiteninhalte hinterlegt werden können. (könnte man evtl. mittels der blocks aus dem theme lösen)
- Erst darunter soll die Auflistung aller in dieser Kategorie enthaltenen Produkte erfolgen (gibt es ja bereits)

Subnavigations-Seiten: (vgl. hier https://www.jalousiescout.de/gurtwickler/elektrische-gurtwickler)
- an oberster Stelle ebenfalls eine Auswahl-Navigation über die verfügbaren Unterpunkte enthalten.
- darunter soll die  Auflistung aller in dieser Kategorie enthaltenen Produkte erfolgen (gibt es ja bereits)
- Erst darunter sollen dann nochmal umfangreiche Texte und Seiteninhalte hinterlegt werden können.

Kannst du mir dazu auch eine Einschätzung abgegeben bitte? Ich denke zwar es ist mit Bordmitteln lösbar, aber evtl. irre ich mich auch.

**Comment by kellerfelix** [comment]
Update: Im Flatsome Template besteht die Möglichkeit bei dem "Produktkatalog" die Anezige für die Shop-Seite und für die Kategorien entsprechend anzupassen mit der Option: "Kategorien & Produkte anzeigen" sowie "Unterkategorien & Produkte anzeigen". Das bewirkt genau dass die Produkt-Kategorien zuerst angezeigt werden!
Es würde also nur noch ein Styling der Anzeige sowie die Möglichkeit der TEXT-Einstellung unterhalt dieser Optionen fehlen (derzeit sind die Bilder noch breite-Füllend und alle Kategorien werden untereinander dargestellt, statt nebeneinander.) 
![image](https://user-images.githubusercontent.com/8479367/73445668-80c99180-435b-11ea-8dc8-c36146355422.png)

Könntest du daher bitte deine Einschätzung anhand dieser Informationen geben:
- Anpassung/Styling der Kategorien: maximal 4 nebeneinander in einer Reihe. Gestaltung der Unterkategorie-Darstellung kann ansonsten gleich bleiben
- Einfügen eines Inhalts-Bausteins für jede Kategorie (z.b. via Theme eigenen "Blocks)

**Comment by hyphone** [comment]
Kategorie-Ansicht:
- Unterkategorien (3 Bilder nebeneinander)
- Kategorie-Text
- Produkte

**Comment by hyphone** [comment]
Das Template ist auf Staging vorbereitet.
Wenn die "Anzeigeart" der Produkt-Kategorie auf "beides" gesetzt ist, wird es nun so angezeigt: 

![Bildschirmfoto von 2020-02-07 16-27-07](https://user-images.githubusercontent.com/6410852/74041902-d559b600-49c6-11ea-876b-55d2e861f2d7.png)

**Comment by kellerfelix** [comment]
Eben gesehen. Bei Bedienelementen sieht das schon gut aus. Ist aber scheinbar die einzige Kategorie, in der das so aussieht?!

**Comment by hyphone** [comment]
Genau, siehe oberen Kommentar:

> Wenn die "Anzeigeart" der Produkt-Kategorie auf "beides" gesetzt ist, wird es nun so angezeigt

Beschreibung ist die Kategorie-Beschreibung.

**Comment by kellerfelix** [comment]
Alles klar. Ist umgestellt und sieht gut aus. Gerne würde ich die Ansicht noch verbessern durch:

- Titel der Kategorie auf der rechten Seite über der Auswahl der Unterkategorien anzeigen. Derzeit via Theme Customizer versteckt (h1). Ebenfalls als H1 Darstellen.
- ist es möglich für die Unterkategorien dieselbe Höhe für die Layover zu setzen? Derzeit richtet sich diese nach der Länge des Kategorie-Textes.
![image](https://user-images.githubusercontent.com/8479367/74054951-54f37f00-49df-11ea-9927-c72a295d50c2.png)

- Außerdem wäre die Frage ob wir standardmäßig noch einen Button auf dieser weißen Fläche mit reinnehmen BZW. alternativ den Titel der Kategorie selbst als solchen darstellen. Nicht dass jemandem nicht klar ist, dass er darauf klicken kann.
Vgl. dazu jalousiescout (Konkurrenz):
![image](https://user-images.githubusercontent.com/8479367/74054987-68064f00-49df-11ea-8fa8-e6d516f77d60.png)

**Comment by hyphone** [comment]
@kellerfelix magst du mal schauen ob das so passt?

https://staging.mein-rollladenshop.de/gurte/

**Comment by kellerfelix** [comment]
Hi @hyphone ,

ja, sieht gut aus. Einzig der Button: Ist der Innen-Abstand vom Text nach oben unten zur umschließenden Box gleich hoch? Sieht bei mir aus, als wäre unter dem Text mehr space. Bitte korrigieren. Ansonsten super! Vielen Dank!

**Comment by hyphone** [comment]
@kellerfelix hatte absichtlich weniger Abstand (Hälfte) hinzugefügt, damit die Box nicht noch größer wird und der Textblock zusammengehöriger erscheint.

Habe es nun in etwa gleichgesetzt.

Wenn das so passt, stelle ich das schonmal live.

**Comment by kellerfelix** [comment]
Hi @hyphone ,

habe es mir nochmal angesehen. Sieht super aus. Eine Kleinigkeit noch:

Mobile werden die Kategorien nach 3 umgebrochen. Könntest du diese hier auf 2 begrenzen?
Dann wird das alles wieder etwas größer und besser erkennbar.

Ansonsten sieht soweit alles gut aus!

**Comment by hyphone** [comment]
@kellerfelix die Höhe der Überschrift in den weißen Balken habe ich auf 2 Zeilen erhöht. Dies funktioniert i.d.r. auf Desktop. Sicher könnte ich mobile auf 3 Zeilen gehen, dann sieht man aber ggf. nicht mehr viel vom Bild. Man muss hier einen Mittelwert finden. Es sollte aber wieder ok aussehen, wenn man mobil auf 2 Elemente pro Zeile geht.

**Comment by hyphone** [comment]
@kellerfelix auf extrem schmalen Bildschirmen lasse ich den Text nun unter die Grafik wandern. Ab einer Auflösung, in der es sinnvoll wird, ist es wieder im Bild.

[simplescreenrecorder-2020-02-10_17.41.24.zip](https://github.com/kellerfelix/rollladenkonfigurator/files/4181973/simplescreenrecorder-2020-02-10_17.41.24.zip)

**Comment by hyphone** [comment]
@kellerfelix Dies ist so nun Live.

**Comment by kellerfelix** [comment]
Hi @hyphone ,

super, vielen Dank! Hab noch eine kleine Sache entdeckt. Aus irgendeinem Grund ist die neue H1 etwas versetzt nach rechts. Kannst du das bitte noch anpassen? Dann müsste es das gewesen sein :)

![image](https://user-images.githubusercontent.com/8479367/74183121-9f296a00-4c44-11ea-96d2-b7f67704135f.png)

**Comment by hyphone** [comment]
@kellerfelix Hast du den Browser Cache gelöscht?

**Comment by kellerfelix** [comment]
Ja, funktioniert jetzt aber! Top Danke :) @hyphone

**Comment by kellerfelix** [comment]
Kleiner Zusatz wie eben per Email angekündigt:

Last but not least würde ich gerne bei der neuen Subkategorie-Ansicht ggf. noch ein Custom-Feld unterbringen, das sich z.B. über den Visual Composer befüllen lässt. Hintergrund: Die Konfigurierbaren Produkte liegen in einer versteckten Kategorie. Hier würde ich gerne direkt via Bild auf den Inhalt verlinken. Einzige Idee, die mir bisher gekommen ist: In diesem Spezialfall die Sub-Kategorie-Ansicht nicht wählen und dann via block einen Custom Inhalt ähnlich der Darstellung zaubern und einfügen. Meinst du das geht?

![image](https://user-images.githubusercontent.com/8479367/75156086-a60aaf00-5711-11ea-92e5-9f152af943e4.png)

**Comment by hyphone** [comment]
Ich könnte in der Kategorie selbst eine Einstellmöglichkeit erstellen, dass man ein Bild, Text und einen Link hinterlegen könnte.

Das Element soll genauso aussehen, wie die Kästen daneben (Bild, Überschrift, Button)?
