### ISSUE TITLE
P1 - Kategorie ein-ausklapp-Logik

### ISSUE THREAD

**Issue by kellerfelix** [kellerfelix/rollladenkonfigurator#54]
Da unsere neuen Kategorien deutlich mehr Ebenen und Struktur haben, würde ich gerne ein Regel für das Aus- und Einklappen der verschiedenen Kategorien auf der linken Sidebar treffen. 

- Stand im Theme-Standard derzeit: Alle immer eingeklappt. 
- Derzeit testweise mittels Script im Header (Flatsome - Global-Settings) alle ausgeklappt = viel zu viel - unübersichtlich!

- **Gewünscht:** Es wird immer nur alle Unterkategorien der jeweilig gewählte Kategorie erster Ebene komplett ausgeklappt dargestellt. Andere Kategorien erster Ebene verbleiben stets eingeklappt. Sie sollten sich aber auch ausklappen lassen. 
Bonus: Wenn ich eine andere Kategorie 1ster Ebene ausklappe, sollte die alte (evtl. auch aktuelle Kategorie einklappen).
(Siehe Screenshot)
![image](https://user-images.githubusercontent.com/8479367/75156142-c3d81400-5711-11ea-81ac-6c0fc4ebcc12.png)

**Comment by hyphone** [comment]
done on staging

**Comment by kellerfelix** [comment]
Sieht super aus!
