### ISSUE TITLE
P1 - Darstellung Warenkorb (mobile) fehlerhaft

### ISSUE THREAD

**Issue by kellerfelix** [kellerfelix/rollladenkonfigurator#56]
Hallo,

im Warenkorb Mobile fehlen die Zwischensummen und die Gesamtsumme (siehe Screenshot):
![image](https://user-images.githubusercontent.com/8479367/75549469-0a8a7e80-5a30-11ea-8cbf-e024d5a05d4b.png)

**Comment by hyphone** [comment]
fixed

**Comment by kellerfelix** [comment]
Awesome!
