### ISSUE TITLE
59) Darstellungsbug in Schritt 5 (PVC Konfig)

### ISSUE THREAD

**Issue by kellerfelix** [kellerfelix/rollladenkonfigurator#8]
Problembeschreibung:

Seit dem vorletzten Update hat sich die Darstellung in Schritt 5 http://wordpress.p379232.webspaceconfig.de/vorbaurolladen-konfigurator-pvc/ verändert.

![59](https://user-images.githubusercontent.com/8479367/40256568-3083e2d4-5aeb-11e8-91bb-832b45a8771b.JPG)

Hier steht jetzt der Text nicht mehr rechts neben der Checkbox, sondern darunter. Fast so, als wäre hier nur eine fixe Breite pro Option hinterlegt. Hat eventuell etwas mit[ Issue 54](https://github.com/kellerfelix/rollladenkonfigurator/issues/5) zu tun?

Gleiches gilt auch für die Option Insektenschutz darunter. Auch diese sollte bitte wieder rechts neben der Box in komplett verfügbarer Breite (oder ggf. nur 50%) dargestellt werden. Erst danach soll der Text umbrechen.

**Comment by kellerfelix** [comment]
Status 11.06.2018: Still here

**Comment by hyphone** [comment]
@kellerfelix bitte einmal prüfen ob es so überall passt

**Comment by kellerfelix** [comment]
Fixxed. Dankeschön!
