### ISSUE TITLE
Produkt Konfigurator kann nicht in den Warenkorb gelegt werden

### ISSUE THREAD

**Issue by kellerfelix** [kellerfelix/rollladenkonfigurator#9]
Beim testen des zweiten Konfigurators: http://wordpress.p379232.webspaceconfig.de/rolladenpanzer-konfigurator-aluminium/ ist mir gerade aufgefallen, dass es hier aus irgendeinem Grund nicht mehr möglich ist, diesen in den Warenkorb zu legen. Nachdem alles ausgewählt ist, ist die Schaltfläche rechts immer noch matt hinterlegt.
Ist das ein Einrichtungsfehler oder ein Bug?

**Comment by kellerfelix** [comment]
Status 11.06.2018: Still there

**Comment by hyphone** [comment]
@kellerfelix sollte nun funtionieren. Die Validierung wurde nur beim Wechsel eines Schrittes ausgeführt. Nun auch bei jeder Änderung eines Eingabefelds.

**Comment by kellerfelix** [comment]
Super. Klappt jetzt!
